apiVersion: v1
kind: Service
metadata:
  name: fiap-tech-fast-food-svc
spec:
  type: LoadBalancer
  selector:
    app: fiap-tech-fast-food-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
#      nodePort: 31300