version: '3'

services:
  mongoservice:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ${pwd}/docker/volumes/mongodb:/data/db
    networks:
      - mongo-compose-network

  fiap-tech-fast-food:
    image: cosmtrek/air
    working_dir: /project
    ports:
      - 8080:8080
    volumes:
      - ./../../:/project
    networks:
      - mongo-compose-network
    depends_on: 
      - mongoservice

networks: 
    mongo-compose-network:
      driver: bridge