on: [pull_request]
name: Go Unit Test and Coverage

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Create coverage directory
      run: mkdir -p coverage  

    - name: Run tests
      run: go mod tidy && go test ./... -coverprofile=coverage/coverage.out -json ./... > coverage/go-test-report.json

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage

  sonarcloud:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Download coverage report
      uses: actions/download-artifact@v3
      with:
        name: coverage-report
        path: coverage
    
    - name: List files (debugging step)
      run: ls -la coverage

    - name: Show contents of coverage file (debugging step)
      run: cat coverage/go-test-report.json

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
